-- 1. Locations
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL UNIQUE
);

-- 2. Users (Custom Table for Legacy Auth Support)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    registration TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'employee',
    function TEXT DEFAULT '',
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    trainings JSONB DEFAULT '[]'::jsonb,
    is_active BOOLEAN DEFAULT false,
    avatar_url TEXT,
    avatar_position TEXT DEFAULT 'center'
);

-- 3. Activities
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    om_number TEXT,
    operation TEXT,
    model TEXT,
    code TEXT,
    involved_employees JSONB DEFAULT '[]'::jsonb,
    location_id BIGINT REFERENCES locations(id),
    description TEXT,
    status TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_id BIGINT REFERENCES users(id),
    total_active_time INTEGER DEFAULT 0,
    total_paused_time INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Status History
CREATE TABLE IF NOT EXISTS status_history (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    activity_id BIGINT REFERENCES activities(id) ON DELETE CASCADE,
    status TEXT,
    justification TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Messages
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    activity_id BIGINT REFERENCES activities(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id),
    user_name TEXT,
    text TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Occurrences
CREATE TABLE IF NOT EXISTS occurrences (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id BIGINT REFERENCES users(id),
    user_name TEXT,
    title TEXT,
    description TEXT,
    location TEXT,
    type TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    om_number TEXT,
    status TEXT DEFAULT 'Não Solucionado'
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_activities_user_id ON activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_location_id ON activities(location_id);
CREATE INDEX IF NOT EXISTS idx_messages_activity_id ON messages(activity_id);
CREATE INDEX IF NOT EXISTS idx_occurrences_user_id ON occurrences(user_id);

-- Seed Initial Locations (First batch)
INSERT INTO locations (name) VALUES 
('0110 - REDUÇÃO I'), ('0111 - LINHA DE FORNOS RED I'), ('0112 - SALA DE CONTROLE RED I'),
('0113 – SUBESTAÇÃO RED I'), ('0114 - TRATAMENTO PRIMÁRIO DE GASES RED I'), ('0115 – RETIFICAÇÃO RED I'),
('0116 - MANUTENÇÃO LOCAL/SETOR DE REVESTIMENTO RED I'), ('0117 – FERRAMENTARIA RED I'),
('0120 - REDUÇÃO II'), ('0121 - LINHA DE FORNOS RED II'), ('0122 - SALA DE CONTROLE RED II'),
('0123 – SUBESTAÇÃO RED II'), ('0124 - TRATAMENTO PRIMÁRIO DE GASES RED II'), ('0125 – RETIFICAÇÃO RED II'),
('0130 - REDUÇÃO III'), ('0131 - LINHA DE FORNOS RED III'), ('0132 - SALA DE CONTROLE RED III'),
('0133- SUBESTAÇÃO RED III'), ('0134 - TRATAMENTO PRIMÁRIO DE GASES RED III'), ('0135 – RETIFICAÇÃO RED III'),
('0136 - MANUTENÇÃO LOCAL/SETOR DE REVESTIMENTO RED III'), ('0140 - REDUÇÃO IV'), ('0141 - LINHA DE FORNOS RED IV'),
('0142 - SALA DE CONTROLE RED IV'), ('0143 – SUBESTAÇÃO RED IV'), ('0144 - TRATAMENTO PRIMÁRIO DE GASES RED IV'),
('0145 – RETIFICAÇÃO RED IV'), ('0210 - FÁBRICA DE ANODO I'), ('0211 - ANODO VERDE (FAV I)'),
('0212 - ANODO COZIDO (FAC 1)'), ('0213 - CHUMBAMENTO DE HASTES (OCH I)'), ('0214 - MANUTENÇÃO LOCAL / GERENCIA DE OPERAÇÃO'),
('0215 - SUBESTAÇÃO'), ('0216 - ESTOCAGEM DE ANODO VERDE'), ('0220 - FÁBRICA DE ANODO II'),
('0221 - ANODO VERDE (FAV II)'), ('0222 - ANODO COZIDO (FAC II)'), ('0223 - CHUMBAMENTO DE HASTES (OCH II)'),
('0225 - SUBESTAÇÃO'), ('0226 - ESTOCAGEM DE ANODO VERDE'), ('0310 - FUNDIÇÃO I'), ('0312 - SUBESTAÇÃO'),
('0313 - FUNDIÇÃO DE LINGOTES'), ('0314 - MANUTENÇÃO LOCAL / GERENCIA DE OPERAÇÃO'), ('0315 - FUNDIÇÃO DE LINGOTES TIPO "SOW"'),
('0321 - FUNDIÇÃO DE TARUGOS, PLACAS E BARRAS'), ('0322 - SUBESTAÇÃO'), ('0323 - FUNDIÇÃO II'),
('0410 - ESTOCAGEM E ARMAZENAMENTO'), ('0411 - ESTOCAGEM DE ALUMÍNIO'), ('0412 - ESTOCAGEM DE ALUMÍNA, COQUE E PICHE'),
('0413 - ESTOCAGEM DE COMBUSTÍVEIS'), ('0415 - ESTOCAGEM DE ALUMÍNA DO PORTO'), ('0511 - ESTAÇÃO DE TRATAMENTO D\'ÁGUA'),
('0512 - CENTRAL DE AR COMPRIMIDO'), ('0513 - SUBESTAÇÃO PRINCIPAL'), ('0514 - GERAÇÃO DE GÁS DE MADEIRA'),
('0515 - ESTAÇÃO DE TRATAMENTO DE EFLUENTES INDUST.'), ('0516 - CAPTAÇÃO D\'ÁGUA'), ('0517 - GERADOR DE EMERGENCIA'),
('0518 - SUBESTAÇÃO DE UTILIDADES'), ('0519 - MANUTENÇÃO, CONTROLE E OPERAÇÃO DE UTIL.'), ('0520 - ESTAÇÃO DE BOMBEAMENTO DE EFLUENTES'),
('0611 - OFICINA DE MONTAGEM DE CATODOS'), ('0612 -TRATAMENTO DE ESCORIA'), ('0613 - OFICINA DE LIMPEZA DE CADINHOS'),
('0614 - ESCRITÓRIO LOCAL-UNIDADES AUXILIARES'), ('0615 – OFICINA DE MANUTENÇÃO DE SUPERESTRUTURA'),
('0616 - OFICINA DE REFORMAS DE CUBAS E CARCAÇAS'), ('0617 - GARAGEM E MANUTENÇÃO DOS EQUIPAMENTOS'),
('0711 - ADMINISTRAÇÃO GERAL'), ('0712 - VESTIARIO'), ('0713 - REFEITÓRIO'), ('0714 - LABORATÓRIO'),
('0715 - EXPEDIÇÃO E RECEBIMENTO'), ('0716 - CENTRO DE TREINAMENTO'), ('0717 - SEGURANÇA, BANCO, BENEF, VIGILÂNCIA'),
('0718 - ESTAÇÃO DE TRATAMENTO DE ESGOTO DA UN.ADM'), ('0719 - RECRUTAMENTO E AMBULATÓRIO'), ('0720 - CASTELO D\'ÁGUA'),
('0721 - SUBESTAÇÃO'), ('0722 - CENTRO DE PROCESSAMENTO DE DADOS'), ('0723 - HILIPONTO'), ('0725 - RODOVIÁRIA'),
('0811 - DEPARTAMENTO DE ENG. CAPEX/PROJ, ESPECIAIS'), ('0812 - ALMOXARIFADO'), ('0813 - PORTARIA PRINCIPAL'),
('0814 - PORTARIA INDUSTRIAL'), ('0815 - PORTARIA de veiculos'), ('0816 - PORTARIA DE CONTROLE DA ÁREA INDUSTRIAL'),
('0817 - OFICINAS MECÂNICA E CALDEIRARIA'), ('0818 - OFICINA DE VEÍCULOS'), ('0819 - OFICINAS ELÉTRICA E DE INSTRUMENTAÇÃO'),
('0820 - SERVIZOS GERAIS'), ('0821 - SUBESTAÇÃO OFICINAS'), ('0823 - SUBESTAÇÃO ALMOXARIFADO'), ('0824 - BRITAGEM E MOAGEM DE RGC'), ('0911 - INTERCONEXÕES'),
('0912 - INSTALAÇOES PROVISÓRIAS'), ('0920 - SISTEMA LIGAÇÃO AB ELETRONORTE'), ('0921 - LT 230KV ENTRE S.E ΑΘ S.E VILA DO CONDE'),
('0922 - SISTEMA DE COMUNICAÇÃO'), ('0990 - INSTALAÇÕES PORTUÁRIAS')
ON CONFLICT (name) DO NOTHING;
